import type { StaticImageData } from "next/image";

import authorCreateStandard from "@/assets/platform/author-create-standard.jpg";
import authorFeedbackInbox from "@/assets/platform/author-feedback-inbox.jpg";
import authorPilotFoundation from "@/assets/platform/author-pilot-foundation.jpg";
import managerAssignments from "@/assets/platform/manager-assignments.jpg";
import managerOverview from "@/assets/platform/manager-overview.jpg";
import managerReadiness from "@/assets/platform/manager-readiness.jpg";
import managerStandardResults from "@/assets/platform/manager-standard-results.jpg";
import managerTeamProgress from "@/assets/platform/manager-team-progress.jpg";
import staffBriefs from "@/assets/platform/staff-briefs.jpg";
import staffInbox from "@/assets/platform/staff-inbox.jpg";
import staffSequence from "@/assets/platform/staff-sequence.jpg";
import staffServiceRecord from "@/assets/platform/staff-service-record.jpg";
import staffStandards from "@/assets/platform/staff-standards.jpg";
import staffToday from "@/assets/platform/staff-today.jpg";

/* ------------------------------------------------------------------ *
 * The mechanism — the one sentence everything else hangs off.
 * ------------------------------------------------------------------ */

export const mechanism = [
  {
    step: "01",
    key: "standard",
    label: "The standard lives inside the task",
    body: "No binder, no portal, no annual refresher. The operating brief for room 208 is the screen the room attendant is already looking at, on the clock, with the timer running.",
    detail: "Target time · fixed steps · Prepare, Perform, Verify, Release",
  },
  {
    step: "02",
    key: "evidence",
    label: "Doing the work produces the evidence",
    body: "A step marked for photo evidence cannot be ticked until the photo exists. Supervisor sign-off attaches to the same record. Proof is a gate, not a follow-up task.",
    detail: "Photo capture · supervisor sign-off · timestamped, per step",
  },
  {
    step: "03",
    key: "record",
    label: "The evidence compounds into a service record",
    body: "Every completed task adds a line to a defensible history — per person, per standard, per floor, per property. The audit answer is generated by the work, not reconstructed after it.",
    detail: "Audit-ready · per person, per standard, per property",
  },
] as const;

/* ------------------------------------------------------------------ *
 * The six pains — GTM narrative spine.
 * Arc per pain: Status Quo → Impact Chain → The Wound.
 * ------------------------------------------------------------------ */

export type Pain = {
  id: string;
  index: string;
  name: string;
  statusQuo: string;
  impactChain: string;
  wound: string;
  answer: string;
  metric: string;
};

export const pains: Pain[] = [
  {
    id: "supervisor-bottleneck",
    index: "01",
    name: "Supervisor bottleneck",
    statusQuo:
      "One supervisor holds the standard in their head. Every question, every check, every exception routes through them — across fourteen floors, on foot, on a radio.",
    impactChain:
      "The queue forms behind them. Rooms wait on a walk-past. Judgement calls get made without them because waiting costs more than guessing.",
    wound:
      "Your best operator spends the shift being a lookup table instead of running the floor.",
    answer:
      "The standard is in the task, so the routine 90% never needs a human decision. The supervisor gets the exceptions and nothing else.",
    metric: "1 supervisor · 42 staff · 14 floors",
  },
  {
    id: "ghost-sop",
    index: "02",
    name: "Ghost SOP",
    statusQuo:
      "The SOP exists. It is beautifully written, signed off, filed, and printed in a binder near the linen store. Nobody executes it.",
    impactChain:
      "Two attendants reset the same room two different ways. The standard becomes whatever the last person did. Version 6 lives in a PDF nobody has opened since onboarding.",
    wound:
      "You are paying for a standard you cannot prove anyone follows.",
    answer:
      "A standard that isn't inside the timed task isn't a standard — it's a document. Publishing pushes it straight into today's shift.",
    metric: "Written once · executed every shift",
  },
  {
    id: "invisible-performance-gap",
    index: "03",
    name: "Invisible performance gap",
    statusQuo:
      "Ask who your strongest room attendant is and you get an opinion. Ask which of them is actually meeting standard and you get a spreadsheet from last quarter.",
    impactChain:
      "Coaching goes to whoever was seen most recently. Quiet high performers stay invisible; quiet drift stays uncorrected until a guest names it.",
    wound:
      "You cannot manage what you cannot see, so you manage by anecdote.",
    answer:
      "Every task carries a time, a completion state and evidence. Readiness per person and per standard is a live number, not a survey.",
    metric: "Readiness 77% · service health 84%",
  },
  {
    id: "attrition-bleed",
    index: "04",
    name: "Attrition bleed",
    statusQuo:
      "Hospitality turnover is structural. Good staff leave for a better shift pattern and take the institutional knowledge with them.",
    impactChain:
      "The replacement starts from zero with a two-week shadow and a binder. Standards regress to whatever the shadow taught them. The next audit finds the gap.",
    wound:
      "Every departure resets your service quality, and the reset is invisible until a guest pays for it.",
    answer:
      "Knowledge lives in the standards, not in the tenure. A new joiner is executing to spec on day one, with evidence to prove it.",
    metric: "Day-one execution · sequenced unlock",
  },
  {
    id: "star-rating-ceiling",
    index: "05",
    name: "Star rating ceiling",
    statusQuo:
      "Your best rooms are genuinely five-star. Your average room is not. Guests review the variance, not the ceiling.",
    impactChain:
      "Inconsistency caps the rating. The rating caps the rate. Marketing spend buys traffic that a 4.1 converts worse than a 4.6.",
    wound:
      "Inconsistency is a pricing problem wearing an operations costume.",
    answer:
      "The same standard, in the same task, at the same target time, for every room and every shift. Consistency is the product.",
    metric: "Guest signal 85% · variance closed",
  },
  {
    id: "audit-ambush",
    index: "06",
    name: "Audit ambush",
    statusQuo:
      "The brand audit, the health inspection or the franchise review lands with a week's notice. Three people stop operating and start assembling a folder.",
    impactChain:
      "Photos are pulled from WhatsApp. Sign-offs are re-created from memory. The evidence pack is a narrative, not a record — and everyone in the room knows it.",
    wound:
      "You have done the work. You just cannot prove it, which in an audit is the same thing.",
    answer:
      "The record was written while the work happened. The audit is a filter on data you already hold, not a fire drill.",
    metric: "Evidence per step · exportable history",
  },
];

/* ------------------------------------------------------------------ *
 * Three role interfaces.
 * ------------------------------------------------------------------ */

export type Screen = {
  src: StaticImageData;
  title: string;
  caption: string;
  alt: string;
};

export type Role = {
  id: "staff" | "manager" | "author";
  name: string;
  device: "phone" | "desktop";
  deviceLabel: string;
  persona: string;
  personaRole: string;
  headline: string;
  headlineAccent: string;
  summary: string;
  capabilities: { title: string; body: string }[];
  screens: Screen[];
};

export const roles: Role[] = [
  {
    id: "staff",
    name: "Staff",
    device: "phone",
    deviceLabel: "Mobile-first · built for a 340px viewport",
    persona: "Maya Fernando",
    personaRole: "Room attendant · Housekeeping",
    headline: "The whole standard,",
    headlineAccent: "on the clock, in one hand.",
    summary:
      "This is where the product is won or lost. One thumb, one shift, bright daylight, cheap Android, hotel wifi. The timed task is the interface — the standard is inside it, and the evidence comes out of it.",
    capabilities: [
      {
        title: "The timed task",
        body: "Target time, a live countdown and four phases — Prepare, Perform, Verify, Release. Progress is visible before the door opens.",
      },
      {
        title: "Evidence as a gate",
        body: "Steps that require photo proof cannot be ticked without it. Quality evidence is captured by doing the job, not chasing it afterwards.",
      },
      {
        title: "Sequenced readiness",
        body: "Operating briefs unlock in the order the work actually happens, so each proof point supports the next responsibility.",
      },
      {
        title: "A record they own",
        body: "Their service record travels with them — verified standards, supervisor notes, a five-star readiness score they can see rising.",
      },
    ],
    screens: [
      {
        src: staffToday,
        title: "Today",
        caption: "Next timed task, live countdown, shift rhythm",
        alt: "Focus Realm staff mobile screen showing the next timed task for room 208 with a live countdown and shift timeline",
      },
      {
        src: staffSequence,
        title: "Sequence",
        caption: "Briefs unlock in the order the work happens",
        alt: "Focus Realm staff mobile screen showing a role sequence of operating briefs unlocking in order for the rooms division",
      },
      {
        src: staffStandards,
        title: "Standards",
        caption: "Every operating standard, searchable by role",
        alt: "Focus Realm staff mobile screen showing a searchable library of operating standards filtered by job role",
      },
      {
        src: staffServiceRecord,
        title: "Service record",
        caption: "Readiness, phase breakdown, verified credentials",
        alt: "Focus Realm staff mobile screen showing a five-star readiness score with a phase-by-phase service record breakdown",
      },
      {
        src: staffBriefs,
        title: "Briefs",
        caption: "Operating briefs with an inline readiness check",
        alt: "Focus Realm staff mobile screen showing operating briefs with an inline readiness check",
      },
      {
        src: staffInbox,
        title: "Inbox",
        caption: "Assignments and supervisor feedback in one line",
        alt: "Focus Realm staff mobile screen showing assignments, supervisor feedback and reminders in one inbox",
      },
    ],
  },
  {
    id: "manager",
    name: "Manager",
    device: "desktop",
    deviceLabel: "Desktop-primary · the live service picture",
    persona: "Elena Rossi",
    personaRole: "Operations manager",
    headline: "Put attention",
    headlineAccent: "where service needs it.",
    summary:
      "Oversight without the walk-past. Who needs a decision right now, what each role can actually deliver today, and which standards are moving five-star performance — on one screen, refreshed by the floor itself.",
    capabilities: [
      {
        title: "The live service picture",
        body: "Readiness, service health and guest signal sit together, so the next decision carries its property context.",
      },
      {
        title: "Assignment, not chasing",
        body: "Push a standard to a role, a floor or a person. The assignment desk shows what landed and what has not started.",
      },
      {
        title: "Exception handling",
        body: "The routine work clears itself. What surfaces is the blocked room, the missed target and the person who needs a decision.",
      },
      {
        title: "Standard-level results",
        body: "See which standards are lifting performance and which are quietly being worked around — per standard, not per person.",
      },
    ],
    screens: [
      {
        src: managerOverview,
        title: "Overview",
        caption: "One hotel, every promise visible",
        alt: "Focus Realm manager desktop overview showing readiness, service health and guest signal for Aurora Grand Colombo",
      },
      {
        src: managerAssignments,
        title: "Assignments",
        caption: "Push a standard to a role, floor or person",
        alt: "Focus Realm manager desktop assignments screen for pushing operating standards to roles and people",
      },
      {
        src: managerReadiness,
        title: "Readiness status",
        caption: "Who is cleared for which standard",
        alt: "Focus Realm manager desktop screen showing staff readiness status against operating standards",
      },
      {
        src: managerTeamProgress,
        title: "Team progress",
        caption: "Performance made visible, per person",
        alt: "Focus Realm manager desktop team progress screen showing per-person performance against standards",
      },
      {
        src: managerStandardResults,
        title: "Standard results",
        caption: "Which standards actually move the needle",
        alt: "Focus Realm manager desktop screen showing results per operating standard",
      },
    ],
  },
  {
    id: "author",
    name: "Author",
    device: "desktop",
    deviceLabel: "Desktop-only · where the standard is written",
    persona: "Amina Rahman",
    personaRole: "Standards author",
    headline: "Turn the standard into",
    headlineAccent: "a clear shift sequence.",
    summary:
      "Write the instruction, attach the reference photo, define the final checklist, mark which steps demand evidence. Publish, and it is in tonight's shift — no approval maze, no drag-and-drop theatre.",
    capabilities: [
      {
        title: "Subtraction-first authoring",
        body: "A form, not a page builder. Identity, steps, evidence markers, target time. Everything else was removed on purpose.",
      },
      {
        title: "Evidence by design",
        body: "The author decides where proof is mandatory. That decision becomes a hard gate on the floor, the same day.",
      },
      {
        title: "Publish straight to the shift",
        body: "Publishing adds the standard to the staff library and the manager's assignment desk in one action.",
      },
      {
        title: "The loop closes",
        body: "Feedback and questions from the floor route back to the author of that exact standard, with its version attached.",
      },
    ],
    screens: [
      {
        src: authorCreateStandard,
        title: "Create standard",
        caption: "Instruction, reference photo, final checklist",
        alt: "Focus Realm author desktop screen for creating an operating standard with identity, department and audience role",
      },
      {
        src: authorFeedbackInbox,
        title: "Feedback inbox",
        caption: "The floor answers back, per standard",
        alt: "Focus Realm author desktop feedback inbox showing responses from staff per operating standard",
      },
      {
        src: authorPilotFoundation,
        title: "Pilot foundation",
        caption: "One property, one pilot, thirty days",
        alt: "Focus Realm author desktop pilot foundation screen configuring a single-property pilot",
      },
    ],
  },
];

/* ------------------------------------------------------------------ *
 * Positioning discipline — this is not an LMS.
 * ------------------------------------------------------------------ */

export const vocabulary = [
  { avoid: "course", use: "operating brief" },
  { avoid: "module", use: "timed task" },
  { avoid: "learner", use: "staff on shift" },
  { avoid: "completion", use: "evidence" },
  { avoid: "training platform", use: "service execution platform" },
  { avoid: "LMS", use: "service record" },
] as const;

/* ------------------------------------------------------------------ *
 * Demo environment — one fictional property, always.
 * ------------------------------------------------------------------ */

export const property = {
  name: "Aurora Grand Colombo",
  location: "Colombo, Sri Lanka",
  staff: 42,
  floors: 14,
  routes: 27,
} as const;

export const personas = [
  { name: "Maya Fernando", role: "Room attendant", role_interface: "Staff", initials: "MF" },
  { name: "Elena Rossi", role: "Operations manager", role_interface: "Manager", initials: "ER" },
  { name: "Amina Rahman", role: "Standards author", role_interface: "Author", initials: "AR" },
  { name: "Arjun Rao", role: "Duty manager", role_interface: "Manager", initials: "AR" },
  { name: "Jonas Lee", role: "Incoming shift", role_interface: "Staff", initials: "JL" },
] as const;

/* ------------------------------------------------------------------ *
 * Team.
 * ------------------------------------------------------------------ */

export type Person = {
  slug: string;
  name: string;
  role: string;
  shortRole: string;
  initials: string;
  /**
   * Drop a square portrait at assets/team/<slug>.jpg and import it here.
   * Until one exists the monogram avatar renders instead.
   */
  photo?: StaticImageData;
  headline: string;
  bio: string[];
  focus: string[];
  traits: { title: string; body: string }[];
  quote: string;
  /** Public profiles. Emitted as schema.org sameAs — the strongest signal
   *  tying a founder's name query to this site. Add the real URLs. */
  sameAs?: string[];
};

/**
 * Canonical order — Sehej first. This is the order used on /team and /about.
 * The home page uses `teamHomeOrder` so the CEO sits centre of the three-up.
 */
export const team: Person[] = [
  {
    slug: "sehej-sharma",
    name: "Sehej Sharma",
    role: "Co-Founder & Chief Executive Officer",
    shortRole: "Co-Founder & CEO",
    initials: "SS",
    headline: "The trailblazer who decided the standard belongs inside the shift.",
    bio: [
      "Sehej Sharma is the Co-Founder and Chief Executive Officer of Focus Realm Hospitality, the service execution platform for hotel operations. He sets the company's direction, owns its positioning, and leads it from the front of the room — in front of general managers, HR directors and heads of learning who have heard every training pitch there is.",
      "He is the author of the thesis the entire platform is built on: a standard that does not live inside the timed task is not a standard, it is a document. That idea was not a refinement of an existing category — it was a rejection of one. Under his direction Focus Realm retired its training-platform framing completely and rebuilt around service execution and evidence, a call that cost the company an easier story and bought it a defensible one.",
      "That is the pattern in how he leads. He is execution-first: an opinion that has not been shipped, sold or survived contact with a real floor does not count. He would rather take a decision on Monday and be corrected by Thursday than hold a committee until the quarter closes. It makes him a fast, deliberate risk-taker — the kind who moves a whole company off a comfortable category because the uncomfortable one is true.",
      "He is also, unusually for a founder at this stage, disciplined about language. He polices the vocabulary of the company personally, because he understands that positioning is not marketing decoration — it is the constraint that decides what gets built. Every word on this site passed through that filter.",
      "He works property by property, floor by floor, with the operators who carry the consequence: the general manager whose rating is capped by inconsistency, the HR director watching institutional knowledge walk out the door, the L&D head whose sessions have attendance sheets and no execution signal. The six pains Focus Realm sells against were not workshopped. He collected them one conversation at a time.",
      "The ambition is not a better tool for hotels. It is the operating layer that hotel service standards run on — a category Focus Realm intends to define and then own.",
    ],
    traits: [
      {
        title: "Trailblazer",
        body: "Named and built a category rather than competing inside one that already had incumbents and rules he did not agree with.",
      },
      {
        title: "Execution first",
        body: "Ideas are cheap and he treats them that way. What counts is shipped, on a floor, with evidence attached.",
      },
      {
        title: "Deliberate risk-taker",
        body: "Retired a working, sellable framing mid-flight because the honest one would compound and the comfortable one would not.",
      },
      {
        title: "Visionary operator",
        body: "Holds the ten-year picture — standards as infrastructure — and the Tuesday-morning decision in the same head.",
      },
    ],
    focus: ["Category & positioning", "Product thesis", "Go-to-market", "Hospitality partnerships", "Founder-led sales"],
    quote:
      "Standards stop being a document nobody reads the moment they become the unit of work a staff member is doing right now.",
  },
  {
    slug: "ali-electricwala",
    name: "Ali Electricwala",
    role: "Co-Founder & Chief Operating Officer",
    shortRole: "Co-Founder & COO",
    initials: "AE",
    headline: "The operator who makes a standard survive week three.",
    bio: [
      "Ali Electricwala is the Co-Founder and Chief Operating Officer of Focus Realm Hospitality. He owns how the platform actually lands inside a working hotel — pilot design, rollout, and the operating discipline that keeps a standard alive after the launch enthusiasm wears off.",
      "His work starts where most operations software stops: the floor. Shift patterns, supervisor load, the realities of a large property running on staff-owned phones and mobile data. Every pilot Focus Realm runs is scoped so that a property sees evidence accumulating inside the first thirty days — not a rollout plan, actual timestamped proof.",
      "He leads commercial operations and customer success, and he is the route by which the floor's reality gets back into the roadmap. When a standard is being worked around rather than worked, he is usually the first person in the company to know.",
    ],
    traits: [
      {
        title: "Rollout discipline",
        body: "Designs pilots backwards from the evidence a property must be holding on day thirty.",
      },
      {
        title: "Floor-level realism",
        body: "Scopes to the shift that exists, not the org chart that describes it.",
      },
      {
        title: "Customer proximity",
        body: "Stays close enough to the property to hear a standard failing before a report does.",
      },
    ],
    focus: ["Pilot design & rollout", "Customer success", "Commercial operations", "Property onboarding"],
    quote: "A standard that survives week three is an operating decision, not a document decision.",
  },
  {
    slug: "aditya-mishra",
    name: "Aditya Mishra",
    role: "Co-Founder & Chief Technology Officer",
    shortRole: "Co-Founder & CTO",
    initials: "AM",
    headline: "The architect who removes things until the task is all that is left.",
    bio: [
      "Aditya Mishra is the Co-Founder and Chief Technology Officer of Focus Realm Hospitality. He drives the platform's subtraction-first design principle: every screen earns its place, and anything that does not help a staff member finish the task in front of them gets removed before it ships.",
      "He architected Focus Realm as three deliberately separate role interfaces — a mobile-first staff experience built for a 340px viewport, a desktop-primary manager surface, and a desktop-only authoring workspace — rather than one responsive layout that would have been cheaper to build and worse in all three postures.",
      "The platform runs on Google Cloud and Firebase: web-based, on standard browsers over mobile data, with no high-end hardware and no PMS integration required at this stage. That is a deliberate constraint, not a gap. The product has to work on the phone a room attendant already owns, in daylight, on hotel wifi — and if it does not work there, it does not work.",
    ],
    traits: [
      {
        title: "Subtraction first",
        body: "Measures a release by what came out of it as much as what went in.",
      },
      {
        title: "Constraint-led architecture",
        body: "Three interfaces instead of one compromise, because the postures have nothing in common.",
      },
      {
        title: "Built for the worst device",
        body: "Targets the cheapest phone on the weakest network, so everything above it is free.",
      },
    ],
    focus: ["Subtraction-first design", "Platform architecture", "Google Cloud & Firebase", "Mobile performance"],
    quote:
      "The hardest engineering problem here is a 340px screen held in one hand, in daylight, on hotel wifi.",
  },
];

/** Home-page order: the CEO sits in the centre of the three-up. */
export const teamHomeOrder: Person[] = [team[1], team[0], team[2]];

export function personBySlug(slug: string) {
  return team.find((entry) => entry.slug === slug);
}

/* ------------------------------------------------------------------ *
 * Market & references.
 * ------------------------------------------------------------------ */

export const buyers = [
  {
    title: "General Managers",
    pain: "Inconsistency caps the property's rating, and the rating caps the rate.",
    win: "One live service picture, and a defensible record behind every promise.",
  },
  {
    title: "HR Directors",
    pain: "Turnover resets service quality, and onboarding is a two-week shadow.",
    win: "Day-one execution to spec, with readiness visible per person.",
  },
  {
    title: "Heads of Learning & Development",
    pain: "Spray-and-pray sessions with attendance sheets and no execution signal.",
    win: "Standards that execute on the floor and report back what worked.",
  },
] as const;

/**
 * Trusted-by strip. Add a logo at assets/clients/<file>.png and import it as
 * `logo` — the wordmark tile renders until one exists.
 */
export type Client = {
  name: string;
  segment: string;
  logo?: StaticImageData;
  note?: string;
};

export const clients: Client[] = [
  {
    name: "Clarks Amer",
    segment: "Hotel chains",
    note: "Hotel & Brij Convention Centre",
  },
  { name: "Renu Mehra's", segment: "Corporate trainers", note: "'ALL' of finesse" },
  { name: "D.A.V. Sr. Sec. School", segment: "Reputed schools", note: "Jaipur" },
  { name: "Recharga", segment: "Fast-growing startups" },
  { name: "TwoKey", segment: "Premium SaaS teams" },
  { name: "The Hosteller", segment: "Distributed properties" },
];

/**
 * Client words, quoted as given. The Clarks quote predates the repositioning
 * and uses the retired category noun — it is left verbatim because a
 * testimonial is attributed speech, not our own positioning.
 */
export const testimonials = [
  {
    quote:
      "Focus Realm provided a flexible LMS solution that improved staff training, automated compliance tracking, and enhanced reporting efficiency across multiple hotel properties.",
    author: "Clarks Hotels & Resorts",
    role: "Multi-property hotel group",
    tag: "Multi-property operations",
  },
  {
    quote:
      "Focus Realm helped us implement outcome-driven AI training programs, significantly improving employee efficiency, engagement, and real-world AI adoption.",
    author: "TwoKey",
    role: "SaaS product team",
    tag: "Capability & upskilling",
  },
] as const;

/* ------------------------------------------------------------------ *
 * Sales material: what changes, and what we are not.
 * ------------------------------------------------------------------ */

export const outcomes = [
  {
    stat: "Day 1",
    label: "New joiners executing to spec",
    body: "No two-week shadow. The standard is on the phone, timed, with the evidence gate in place from the first room.",
  },
  {
    stat: "30 days",
    label: "Defensible evidence in hand",
    body: "A pilot is scoped so a property is holding timestamped photo and sign-off history before the first month closes.",
  },
  {
    stat: "0",
    label: "Integrations required",
    body: "No PMS project, no hardware, no IT lead time. Standard browsers on the phones your team already carries.",
  },
  {
    stat: "1 screen",
    label: "The whole service picture",
    body: "Readiness, service health and guest signal together, so the next decision carries its property context.",
  },
] as const;

export const comparison = {
  columns: ["Paper, Excel & WhatsApp", "A generic LMS", "Focus Realm"],
  rows: [
    {
      criterion: "Where the standard lives",
      values: ["A binder near the linen store", "A course a staff member watched once", "Inside the timed task, on shift"],
    },
    {
      criterion: "What completion proves",
      values: ["Someone said it was done", "Someone finished a module", "The step was executed, with a photo"],
    },
    {
      criterion: "Evidence capture",
      values: ["Photos scattered in chat", "Quiz scores", "Mandatory per-step, timestamped"],
    },
    {
      criterion: "Supervisor load",
      values: ["Every question routes through one person", "Unchanged — it is not an ops tool", "Exceptions only; routine work clears itself"],
    },
    {
      criterion: "Audit preparation",
      values: ["A week of assembling a folder", "Attendance reports nobody asked for", "A filter on data you already hold"],
    },
    {
      criterion: "When a good person leaves",
      values: ["The knowledge leaves too", "The course stays; the execution does not", "The standard stays, and still executes"],
    },
  ],
} as const;

/** Objection handling — the four things buyers actually push back on. */
export const objections = [
  {
    q: "“Our staff will not use another app.”",
    a: "They are not adopting an app, they are opening the task they were already assigned. One screen, one thumb, the timer already running. If it needs training to use, we built it wrong.",
  },
  {
    q: "“We already have an LMS.”",
    a: "Keep it. An LMS records that someone consumed a course. Focus Realm records that room 208 was reset to standard at 08:36 with a photo attached. Those answer different questions, and only one of them survives an audit.",
  },
  {
    q: "“IT will take six months to approve this.”",
    a: "There is nothing to approve. No PMS integration, no server, no hardware — a browser on the phones your team already owns. Pilots start on a property, not on a roadmap.",
  },
  {
    q: "“Our standards are not written down properly yet.”",
    a: "That is the normal starting point. Bring the standard nobody follows and we will author it live on the call — instruction, reference photo, checklist, evidence gates — and put it on a phone before we hang up.",
  },
] as const;

export const faqs = [
  {
    q: "What is Focus Realm Hospitality?",
    a: "Focus Realm Hospitality is a mobile-first service execution platform for hotel operations. The operating standard lives inside a timed task on the staff member's phone; completing that task captures photo and supervisor evidence; and that evidence compounds into an audit-ready service record for the property.",
  },
  {
    q: "Is Focus Realm a hotel LMS or a training platform?",
    a: "No. Focus Realm is a service execution platform, not a learning management system. An LMS records that someone consumed a course. Focus Realm records that a specific standard was executed on a specific room at a specific time, with photo evidence and supervisor sign-off attached.",
  },
  {
    q: "How does Focus Realm handle SOP management for hotels?",
    a: "Standards are authored once in the Author workspace — instruction, reference photo, final checklist, target time, and which steps require photo evidence. Publishing pushes the standard directly into the staff library and the manager's assignment desk, so it is executable on the next shift rather than filed as a document.",
  },
  {
    q: "What evidence does the platform capture?",
    a: "Per step: a timestamp, completion state, photo evidence where the author marked it mandatory, and supervisor sign-off. A step that requires a photo cannot be ticked until the photo is captured, so the evidence trail is a gate rather than an afterthought.",
  },
  {
    q: "Does Focus Realm need a PMS integration?",
    a: "No. Focus Realm runs independently of the property management system by design at this stage. It is web-based, runs on standard browsers over mobile data, and requires no high-end hardware — which matters when the interface is a room attendant's own phone.",
  },
  {
    q: "Who are the three role interfaces for?",
    a: "Staff use a mobile-first interface built for a 340px viewport, where the timed task and evidence capture happen. Managers use a desktop-primary interface for oversight, assignment and exception handling. Authors use a desktop-only workspace to build and version standards.",
  },
  {
    q: "How does a Focus Realm pilot work?",
    a: "A pilot is scoped to a single property so evidence starts accumulating inside the first thirty days: standards authored for the priority departments, staff executing timed tasks on their own phones, and a manager-side service picture that is live from week one.",
  },
  {
    q: "Who founded Focus Realm Hospitality?",
    a: "Focus Realm Hospitality was founded by Sehej Sharma (Co-Founder & CEO) and Ali Electricwala (Co-Founder & COO), with Aditya Mishra as Chief Technology Officer.",
  },
] as const;
